pipeline {
	agent any
	
	stages {
		stage('Publish Data') {
			steps {
				checkout scm
				publishReport reportFile: "etc/result.json"
				publishReport reportFile: "etc/result-mix.json"
				publishReport reportFile: "etc/result-oc.json"
			}
		}
	}
}
