pipeline {
	agent any
	
	stages {
		stage('Publish Data') {
			steps {
				checkout scm
				publishReport reportFile: "etc/result.json", displayType: "dual"
				publishReport reportFile: "etc/result-oc.json", displayType: "dual"
			} 
		}
	}
}
